theme: jekyll-theme-minimal
title: Giuseppe Persiano
description: Chatting and drinking in Florence, March 2025<p>Home page for my research and teaching <p> My Google scholar <a href=https://scholar.google.it/citations?user=wbQQcfQAAAAJ>entry</a><br>My DBLP <a href=https://dblp.uni-trier.de/pers/hd/p/Persiano:Giuseppe.html>entry</a>
logo: ./firenze-small.png

