theme: jekyll-theme-minimal
title: Giuseppe Persiano
description: Home page for my research and teaching<ul><li>My Google scholar <a href=https://scholar.google.it/citations?user=wbQQcfQAAAAJ>entry</a><li>My DBLP <a href=https://dblp.uni-trier.de/pers/hd/p/Persiano:Giuseppe.html>entry</a></ul>
logo: ./varsavia.jpg

